In [2]:
import numpy as np

In [4]:
arr=np.array([0,3,4,5,6])

In [5]:
arr

array([0, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [12]:
arr1=np.array([[0,3,4,5,6],[7,2,5,6,8]])

In [14]:
print(arr1)

[[0 3 4 5 6]
 [7 2 5 6 8]]


In [20]:
print(arr1.ndim)

2


In [21]:
print(arr1.shape)

(2, 5)


In [22]:
print(arr1.size)

10


In [23]:
print(arr1.dtype)

int64


In [28]:
arr3=np.array([0,3,4,5,65],dtype=np.float64)
print(arr3)

[ 0.  3.  4.  5. 65.]


In [9]:
#arrays of zeros
np.zeros(6)
arr4=print(np.zeros((2,3),dtype=int))

[[0 0 0]
 [0 0 0]]


In [10]:
#arrays of ones
arr4=print(np.ones((2,3),dtype=int))

[[1 1 1]
 [1 1 1]]


In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [52]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

In [17]:
np.full((2,2),7)#fill with 7

array([[7, 7],
       [7, 7]])

In [18]:
np.eye(3)
#identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [8]:
iden=np.eye(3,dtype=int)
print(iden)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
iden2=np.eye(3,dtype=int,k=-1)
print(iden2)

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [23]:
np.empty(4)

array([2., 4., 6., 8.])

In [48]:
np.empty((3,3),dtype=int)

array([[426111328,         0,         0],
       [        0,         0,         0],
       [        0,         0,         0]])

In [29]:
rand=np.random.rand(2,2)
print(rand)

[[0.78578731 0.41794057]
 [0.74862684 0.73679175]]


In [32]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [34]:
arr[4]

50

In [35]:
arr[3::]

array([40, 50])

In [37]:
arr[::4]

array([10, 50])

In [28]:
mat=np.array([[10,20,30],[40,50,60],[3,2,1]])
print(mat)
print(mat.shape)
print(mat.ndim)

[[10 20 30]
 [40 50 60]
 [ 3  2  1]]
(3, 3)
2


In [45]:
print(mat[0])

[10 20 30]


In [29]:
print(mat[:,2])

[30 60  1]


In [53]:
mat1=np.array([[[10,20,30],[40,50,60]],[[3,2,1],[4,5,6]]])
print(mat1)
print(mat1.shape)
print(mat1.ndim)
print(mat[0])


[[[10 20 30]
  [40 50 60]]

 [[ 3  2  1]
  [ 4  5  6]]]
(2, 2, 3)
3
[10 20 30]
[30 60  1]


In [61]:
print(mat1[1,1,1:3])

[5 6]


In [62]:
#Reshaping numpy array
mat=np.array([[10,20,30],[40,50,60]])
print(mat)

[[10 20 30]
 [40 50 60]]


In [72]:
mat=np.array([[10,20,30],[40,50,60]])
mat_reshaped=mat.reshape(3,2)
flat=mat.ravel()
print('original\n',mat)
print('reshaped\n',mat_reshaped)
print('flattened array\n',flat)

original
 [[10 20 30]
 [40 50 60]]
reshaped
 [[10 20]
 [30 40]
 [50 60]]
flattened array
 [10 20 30 40 50 60]


In [56]:
mat1=np.array([[[10,20,30],[40,50,60]],[[3,2,1],[4,5,6]]])
mat1_reshaped=mat1.reshape(2,2,3)
print('original\n',mat1)
print('reshaped\n',mat1_reshaped)

original
 [[[10 20 30]
  [40 50 60]]

 [[ 3  2  1]
  [ 4  5  6]]]
reshaped
 [[[10 20 30]
  [40 50 60]]

 [[ 3  2  1]
  [ 4  5  6]]]


In [76]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(np.add(x,y))

[5 7 9]
[5 7 9]


In [77]:
print(x*y)
print(np.multiply(x,y))

[ 4 10 18]
[ 4 10 18]


In [78]:
print(np.divide(x,y))

[0.25 0.4  0.5 ]


In [79]:
print(np.power(x,y))

[  1  32 729]


In [80]:
print(np.dot(x,y))

32


In [81]:
#np.mod or np.remainder -- return the remainder
#np.absolute or np.abs --- retturn the absolute value

In [83]:
print(np.sum(x))

6


In [84]:
print(np.mean(x))

2.0


In [85]:
print(np.median(x))
print(np.std(x))

2.0
0.816496580927726


In [86]:
print(np.max(x))

3


In [87]:
print(np.min(x))

1


In [88]:
print(np.sort([3,4,5,2,1,3]))

[1 2 3 3 4 5]


In [89]:
#comparsion operators
print(x==y)#equal to
print(x!=y)#not equal to
print(x<y)
print(x<=y)
print(x>y)
print(x>=y)

[False False False]
[ True  True  True]
[ True  True  True]
[ True  True  True]
[False False False]
[False False False]
