In [23]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
1
(4,)
4
int64


In [24]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [25]:
arr2=np.array([[1,2,3,4],[5,"iter",8,9]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[['1' '2' '3' '4']
 ['5' 'iter' '8' '9']]
2
(2, 4)
8
<U21


In [26]:
type(arr)
type(arr1)
type(arr2)

numpy.ndarray

In [29]:
arr4=np.array([1,2,3,4],dtype=np.float64)
arr5=np.array([1,2,3,4])
print(arr4,"\n",arr5)
print(arr4.dtype,arr5.dtype)

[1. 2. 3. 4.] 
 [1 2 3 4]
float64 int64


In [30]:
arr6=np.array([1,2,3,4],dtype=float)
print(arr6)
print(arr6.dtype)

[1. 2. 3. 4.]
float64


In [31]:
arr7=np.array([1,2,3,4])
float_arr=arr.astype(float)
print(float_arr)
print(float_arr.dtype)

[1. 2. 3. 4.]
float64
