In [1]:
marks = int(input('''Enter marks'(0-100)': '''))
if 0<=marks<=100:
    if marks>=90: print("A")
    elif 75<=marks<=89: print("B")
    elif 50<=marks<=74: print("C")
    else: print("Failed")
else: print("Invalid Range")

Enter marks'(0-100)': -1
Invalid Range


In [2]:
def isprime(n):
    if n<=1:
        return False
    if n==2:
        return True
    for i in range(2,n):
        if n%i==0:
            return False
        else: return True

In [3]:
while True:
    n=(input("Enter digit to check for prime: "))
    if n =="break":
        break
    else: print(isprime(int(n)))

Enter digit to check for prime: 1
False
Enter digit to check for prime: 2
True
Enter digit to check for prime: 3
True
Enter digit to check for prime: 4
False
Enter digit to check for prime: 5
True
Enter digit to check for prime: 6
False
Enter digit to check for prime: 7
True
Enter digit to check for prime: 8
False
Enter digit to check for prime: 9
True
Enter digit to check for prime: 101
True
Enter digit to check for prime: break


In [4]:
import numpy as np
mat = np.arange(1,17).reshape(4,4)
print(mat)
print(mat[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 3  7 11 15]
